### ISSUE TITLE
Crash when taping on speed dial

### ISSUE THREAD

**Issue by frankjoshua** [warrenrhodes/drag_speed_dial#5]
The following assertion was thrown building _FabItem(dirty, dependencies: [MediaQuery]):
Either `message` or `richMessage` must be specified
'package:flutter/src/material/tooltip.dart':
Failed assertion: line 194 pos 16: '(message == null) != (richMessage == null)'

The relevant error-causing widget was: 
  SnackbarManager SnackbarManager:file:///home/josh/development/workspace/aiart/flutter_sketchpad/lib/my_app.dart:28:18
When the exception was thrown, this was the stack: 
#2      new Tooltip (package:flutter/src/material/tooltip.dart:194:16)
#3      _FabItem.build (package:drag_speed_dial/src/drag_speed_dial_widget.dart:115:20)

**Comment by warrenrhodes** [comment]
Sorry for the delay, I'll take a look.

**Comment by warrenrhodes** [comment]
@frankjoshua Fix. Thanks for the report
